# Generated by Django 5.2.6 on 2026-07-12 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('TOLLS', 'Tolls'), ('DRIVER_ALLOWANCE', 'Driver Allowance'), ('PERMITS', 'Permits & Fines'), ('MEALS', 'Meals & Lodging'), ('MISC', 'Miscellaneous')], default='MISC', max_length=50, verbose_name='Expense Type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Financial amount of the expense.', max_digits=10, verbose_name='Amount')),
                ('expense_date', models.DateField(help_text='The date when the expense occurred.', verbose_name='Expense Date')),
                ('remarks', models.TextField(blank=True, help_text='Any additional description or justification for the expense.', verbose_name='Remarks')),
                ('trip', models.ForeignKey(blank=True, help_text='The operational trip during which the expense was incurred. Kept as null if trip is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='trips.trip', verbose_name='Trip')),
                ('vehicle', models.ForeignKey(help_text='The vehicle associated with this expense. Cascades on deletion.', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='vehicles.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_liters', models.DecimalField(decimal_places=2, help_text='Volume of fuel purchased in liters.', max_digits=8, verbose_name='Fuel (Liters)')),
                ('fuel_cost', models.DecimalField(decimal_places=2, help_text='Total cost of the purchased fuel.', max_digits=10, verbose_name='Fuel Cost')),
                ('log_date', models.DateField(help_text='The date when fuel was logged.', verbose_name='Log Date')),
                ('trip', models.ForeignKey(blank=True, help_text='The trip during which the refueling occurred. Kept as null if trip is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_logs', to='trips.trip', verbose_name='Trip')),
                ('vehicle', models.ForeignKey(help_text='The vehicle being refueled. Cascades on deletion.', on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='vehicles.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Fuel Log',
                'verbose_name_plural': 'Fuel Logs',
                'ordering': ['-log_date'],
            },
        ),
    ]
