# Generated by Django 5.2.6 on 2026-07-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Driver's full legal name.", max_length=150, verbose_name='Full Name')),
                ('license_number', models.CharField(help_text='Unique driver commercial driver license (CDL) number.', max_length=50, unique=True, verbose_name='License Number')),
                ('license_category', models.CharField(help_text='Class of commercial license (e.g., Heavy Motor Vehicle, Class A).', max_length=20, verbose_name='License Category')),
                ('license_expiry_date', models.DateField(help_text="Expiration date of driver's license.", verbose_name='License Expiry Date')),
                ('contact_number', models.CharField(help_text='Primary phone/mobile contact number.', max_length=20, verbose_name='Contact Number')),
                ('safety_score', models.DecimalField(decimal_places=2, default=100.0, help_text='Driver safety score rating out of 100.00.', max_digits=5, verbose_name='Safety Score')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_TRIP', 'On Trip'), ('OFF_DUTY', 'Off Duty'), ('SUSPENDED', 'Suspended')], default='AVAILABLE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ['full_name'],
            },
        ),
    ]
