# Generated by Django 5.2.6 on 2026-07-12 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(help_text='Brief summary of the issue (e.g., Engine Tune-up, Oil Change).', max_length=200, verbose_name='Issue')),
                ('description', models.TextField(help_text='Detailed description of the maintenance activities/reasons.', verbose_name='Description')),
                ('maintenance_cost', models.DecimalField(decimal_places=2, help_text='Cost incurred for the maintenance service.', max_digits=10, verbose_name='Maintenance Cost')),
                ('start_date', models.DateField(help_text='Date when the maintenance work commenced.', verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='Date when the maintenance was completed. Leave blank if ongoing.', null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this maintenance task is currently active/ongoing.', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('vehicle', models.ForeignKey(help_text='The fleet vehicle under maintenance. Automatically cascades on vehicle deletion.', on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='vehicles.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
                'ordering': ['-start_date'],
            },
        ),
    ]
