# Generated by Django 5.2.6 on 2026-07-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-created_at'], 'verbose_name': 'Maintenance', 'verbose_name_plural': 'Maintenances'},
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='maintenance_cost',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='actual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual final cost incurred.', max_digits=10, null=True, verbose_name='Actual Cost'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='assigned_technician',
            field=models.CharField(blank=True, help_text='Optional name of the technician performing the service.', max_length=100, verbose_name='Assigned Technician'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated cost for the service.', max_digits=10, verbose_name='Estimated Cost'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='issue_title',
            field=models.CharField(default='', help_text='Brief summary of the issue (e.g., Brake pad replacement).', max_length=200, verbose_name='Issue Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.CharField(choices=[('ROUTINE', 'Routine Service'), ('REPAIR', 'Breakdown Repair'), ('INSPECTION', 'Safety Inspection'), ('TYRES', 'Tyre Service')], default='ROUTINE', max_length=50, verbose_name='Maintenance Type'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='notes',
            field=models.TextField(blank=True, help_text='Any additional remarks/notes about this service.', verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
