# Generated by Django 5.2.6 on 2026-07-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(help_text='Unique vehicle registration plate/number.', max_length=20, unique=True, verbose_name='Registration Number')),
                ('model_name', models.CharField(help_text='Model and manufacturer (e.g., Tata Prima 4025.S).', max_length=100, verbose_name='Model Name')),
                ('vehicle_type', models.CharField(help_text='Type of vehicle (e.g., Heavy Duty Truck, Cargo Van).', max_length=50, verbose_name='Vehicle Type')),
                ('max_load_capacity', models.DecimalField(decimal_places=2, help_text='Maximum load capacity in kilograms (kg).', max_digits=10, verbose_name='Max Load Capacity (kg)')),
                ('current_odometer', models.PositiveIntegerField(default=0, help_text='Current odometer reading in kilometers.', verbose_name='Current Odometer (km)')),
                ('acquisition_cost', models.DecimalField(decimal_places=2, help_text='Cost incurred during vehicle acquisition.', max_digits=12, verbose_name='Acquisition Cost')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_TRIP', 'On Trip'), ('IN_SHOP', 'In Shop'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
            },
        ),
    ]
