# Generated by Django 5.2.6 on 2026-07-12 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Starting location of the trip.', max_length=255, verbose_name='Source')),
                ('destination', models.CharField(help_text='Destination location of the trip.', max_length=255, verbose_name='Destination')),
                ('cargo_weight', models.DecimalField(decimal_places=2, help_text='Weight of the transported cargo in kilograms.', max_digits=10, verbose_name='Cargo Weight (kg)')),
                ('planned_distance', models.DecimalField(decimal_places=2, help_text='Estimated trip distance in kilometers.', max_digits=8, verbose_name='Planned Distance (km)')),
                ('revenue', models.DecimalField(decimal_places=2, help_text='Total revenue generated from the trip.', max_digits=12, verbose_name='Revenue')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DISPATCHED', 'Dispatched'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('driver', models.ForeignKey(help_text='The driver assigned to this trip. Protected from accidental deletion.', on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='drivers.driver', verbose_name='Driver')),
                ('vehicle', models.ForeignKey(help_text='The fleet vehicle assigned to this trip. Protected from accidental deletion.', on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicles.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-created_at'],
            },
        ),
    ]
