# Generated by Django 5.2.6 on 2026-07-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the trip was completed.', null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the trip was dispatched.', null=True, verbose_name='Start Date'),
        ),
    ]
